//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Management
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbHR_ManagementEntities : DbContext
    {
        public DbHR_ManagementEntities()
            : base("name=DbHR_ManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TblEmployee> TblEmployees { get; set; }

        public System.Data.Entity.DbSet<HR_Management.TblEmpDetail> TblEmpDetails { get; set; }
    }
}
