//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEmployee
    {
        public int Id { get; set; }
        public string EmpId { get; set; }
        public string EmpName { get; set; }
        public string EmpEmail { get; set; }
        public string EmpDesignation { get; set; }
        public string CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    }
}
